import Head from 'next/head'
import Lists from '../../components/Lists';
import Image from 'next/image'
import {
  Container,
  Box,
  Text,
  Input,
  Select,
  Button,
 
  Flex,
  ListItem,
  ListIcon,
  ChakraProvider,
  ColorModeProvider,
  useColorMode,
  IconButton,
} from "@chakra-ui/react";
// import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex direction={"column"} minHeight={"100vh"}>
      <Lists />
      {/* <Spacer/> */}
      {/* <Box>
      <SmallCentered />
      </Box> */}
      </Flex>
      
    </>
  )
}